/**
 * 该文件开源版本中 暂未开放源码，但可以免费无限制使用。
 * 【仅此1个文件是未开源的，接口见 widget.d.ts 】
 *
 * 如果需要完整代码，可以访问了解更多：http://mars3d.cn/details.html?id=jcxm-vue
 *
 * 编译日期：2022-5-19
 * 版权所有：Copyright by 火星科技  http://mars3d.cn
 */
(function(Y,Z){"object"===typeof exports&&"object"===typeof module?module.exports=Z(require("vuex"),require("vue"),require("uuid")):"function"===typeof define&&define.amd?define(["vuex",,"uuid"],Z):"object"===typeof exports?exports.ts2js=Z(require("vuex"),require("vue"),require("uuid")):Y.ts2js=Z(Y.vuex,Y.Vue,Y.uuid)})("undefined"!==typeof self?self:this,function(Y,Z,xa){return function(c){function b(d){if(a[d])return a[d].exports;var e=a[d]={i:d,l:!1,exports:{}};c[d].call(e.exports,e,e.exports,b);
e.l=!0;return e.exports}var a={};b.m=c;b.c=a;b.d=function(d,e,f){b.o(d,e)||Object.defineProperty(d,e,{enumerable:!0,get:f})};b.r=function(d){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(d,Symbol.toStringTag,{value:"Module"});Object.defineProperty(d,"__esModule",{value:!0})};b.t=function(d,e){e&1&&(d=b(d));if(e&8||e&4&&"object"===typeof d&&d&&d.__esModule)return d;var f=Object.create(null);b.r(f);Object.defineProperty(f,"default",{enumerable:!0,value:d});if(e&2&&"string"!=
typeof d)for(var h in d)b.d(f,h,function(g){return d[g]}.bind(null,h));return f};b.n=function(d){var e=d&&d.__esModule?function(){return d["default"]}:function(){return d};b.d(e,"a",e);return e};b.o=function(d,e){return Object.prototype.hasOwnProperty.call(d,e)};b.p="";return b(b.s="fae3")}({"00ee":function(c,b,a){b=a("b622")("toStringTag");a={};a[b]="z";c.exports="[object z]"===String(a)},"0366":function(c,b,a){b=a("e330");var d=a("59ed"),e=b(b.bind);c.exports=function(f,h){d(f);return void 0===
h?f:e?e(f,h):function(){return f.apply(h,arguments)}}},"057f":function(c,b,a){var d=a("c6b6"),e=a("fc6a"),f=a("241c").f,h=a("4dae"),g="object"==typeof window&&window&&Object.getOwnPropertyNames?Object.getOwnPropertyNames(window):[];c.exports.f=function(m){if(g&&"Window"==d(m))try{var k=f(m)}catch(l){k=h(g)}else k=f(e(m));return k}},"06cf":function(c,b,a){c=a("83ab");var d=a("c65b"),e=a("d1e7"),f=a("5c6c"),h=a("fc6a"),g=a("a04b"),m=a("1a2d"),k=a("0cfb"),l=Object.getOwnPropertyDescriptor;b.f=c?l:function(n,
q){n=h(n);q=g(q);if(k)try{return l(n,q)}catch(u){}if(m(n,q))return f(!d(e.f,n,q),n[q])}},"07fa":function(c,b,a){var d=a("50c4");c.exports=function(e){return d(e.length)}},"0b42":function(c,b,a){b=a("da84");var d=a("e8b5"),e=a("68ee"),f=a("861d"),h=a("b622")("species"),g=b.Array;c.exports=function(m){if(d(m)){var k=m.constructor;e(k)&&(k===g||d(k.prototype))?k=void 0:f(k)&&(k=k[h],null===k&&(k=void 0))}return void 0===k?g:k}},"0cfb":function(c,b,a){b=a("83ab");var d=a("d039"),e=a("cc12");c.exports=
!b&&!d(function(){return 7!=Object.defineProperty(e("div"),"a",{get:function(){return 7}}).a})},"0d51":function(c,b,a){var d=a("da84").String;c.exports=function(e){try{return d(e)}catch(f){return"Object"}}},"159b":function(c,b,a){c=a("da84");b=a("fdbc");var d=a("785a"),e=a("17c2"),f=a("9112");a=function(g){if(g&&g.forEach!==e)try{f(g,"forEach",e)}catch(m){g.forEach=e}};for(var h in b)b[h]&&a(c[h]&&c[h].prototype);a(d)},1626:function(c,b){c.exports=function(a){return"function"==typeof a}},"17c2":function(c,
b,a){var d=a("b727").forEach;b=a("a640")("forEach");c.exports=b?[].forEach:function(e){return d(this,e,1<arguments.length?arguments[1]:void 0)}},"1a2d":function(c,b,a){b=a("e330");var d=a("7b0b"),e=b({}.hasOwnProperty);c.exports=Object.hasOwn||function(f,h){return e(d(f),h)}},"1be4":function(c,b,a){b=a("d066");c.exports=b("document","documentElement")},"1d80":function(c,b,a){var d=a("da84").TypeError;c.exports=function(e){if(void 0==e)throw d("Can't call method on "+e);return e}},"1dde":function(c,
b,a){var d=a("d039");b=a("b622");var e=a("2d00"),f=b("species");c.exports=function(h){return 51<=e||!d(function(){var g=[];(g.constructor={})[f]=function(){return{foo:1}};return 1!==g[h](Boolean).foo})}},"23cb":function(c,b,a){var d=a("5926"),e=Math.max,f=Math.min;c.exports=function(h,g){h=d(h);return 0>h?e(h+g,0):f(h,g)}},"23e7":function(c,b,a){var d=a("da84"),e=a("06cf").f,f=a("9112"),h=a("6eeb"),g=a("ce4e"),m=a("e893"),k=a("94ca");c.exports=function(l,n){var q=l.target,u=l.global,y=l.stat,B,C,
r;if(C=u?d:y?d[q]||g(q,{}):(d[q]||{}).prototype)for(r in n){var t=n[r];var p=l.noTargetGet?(B=e(C,r))&&B.value:C[r];B=k(u?r:q+(y?".":"#")+r,l.forced);if(!B&&void 0!==p){if(typeof t==typeof p)continue;m(t,p)}(l.sham||p&&p.sham)&&f(t,"sham",!0);h(C,r,t,l)}}},"241c":function(c,b,a){var d=a("ca84"),e=a("7839").concat("length","prototype");b.f=Object.getOwnPropertyNames||function(f){return d(f,e)}},2532:function(c,b,a){c=a("23e7");b=a("e330");var d=a("5a34"),e=a("1d80"),f=a("577e");a=a("ab13");var h=b("".indexOf);
c({target:"String",proto:!0,forced:!a("includes")},{includes:function(g){return!!~h(f(e(this)),f(d(g)),1<arguments.length?arguments[1]:void 0)}})},"25f0":function(c,b,a){var d=a("e330");b=a("5e77").PROPER;c=a("6eeb");var e=a("825a"),f=a("3a9b"),h=a("577e"),g=a("d039");a=a("ad6d");var m=RegExp.prototype,k=m.toString,l=d(a);a=g(function(){return"/a/b"!=k.call({source:"a",flags:"b"})});b=b&&"toString"!=k.name;(a||b)&&c(RegExp.prototype,"toString",function(){var n=e(this),q=h(n.source),u=n.flags;n=h(void 0!==
u||!f(m,n)||"flags"in m?u:l(n));return"/"+q+"/"+n},{unsafe:!0})},"2ba4":function(c,b){b=Function.prototype;var a=b.apply,d=b.bind,e=b.call;c.exports="object"==typeof Reflect&&Reflect.apply||(d?e.bind(a):function(){return e.apply(a,arguments)})},"2d00":function(c,b,a){b=a("da84");a=a("342f");var d=b.process;b=b.Deno;b=(b=d&&d.versions||b&&b.version)&&b.v8;if(b){b=b.split(".");var e=0<b[0]&&4>b[0]?1:+(b[0]+b[1])}!e&&a&&(b=a.match(/Edge\/(\d+)/),(!b||74<=b[1])&&(b=a.match(/Chrome\/(\d+)/))&&(e=+b[1]));
c.exports=e},"342f":function(c,b,a){b=a("d066");c.exports=b("navigator","userAgent")||""},"37e8":function(c,b,a){b=a("83ab");var d=a("9bf2"),e=a("825a"),f=a("fc6a"),h=a("df75");c.exports=b?Object.defineProperties:function(g,m){e(g);var k=f(m);m=h(m);for(var l=m.length,n=0,q;l>n;)d.f(g,q=m[n++],k[q]);return g}},"3a9b":function(c,b,a){b=a("e330");c.exports=b({}.isPrototypeOf)},"3bbe":function(c,b,a){b=a("da84");var d=a("1626"),e=b.String,f=b.TypeError;c.exports=function(h){if("object"==typeof h||d(h))return h;
throw f("Can't set "+e(h)+" as a prototype");}},"3ca3":function(c,b,a){var d=a("6547").charAt,e=a("577e");c=a("69f3");a=a("7dd0");var f=c.set,h=c.getterFor("String Iterator");a(String,"String",function(g){f(this,{type:"String Iterator",string:e(g),index:0})},function(){var g=h(this),m=g.string,k=g.index;if(k>=m.length)return{value:void 0,done:!0};m=d(m,k);g.index+=m.length;return{value:m,done:!1}})},"3f8c":function(c,b){c.exports={}},"428f":function(c,b,a){b=a("da84");c.exports=b},"44ad":function(c,
b,a){b=a("da84");var d=a("e330"),e=a("d039"),f=a("c6b6"),h=b.Object,g=d("".split);c.exports=e(function(){return!h("z").propertyIsEnumerable(0)})?function(m){return"String"==f(m)?g(m,""):h(m)}:h},"44d2":function(c,b,a){b=a("b622");var d=a("7c73");a=a("9bf2");var e=b("unscopables"),f=Array.prototype;void 0==f[e]&&a.f(f,e,{configurable:!0,value:d(null)});c.exports=function(h){f[e][h]=!0}},"44e7":function(c,b,a){var d=a("861d"),e=a("c6b6"),f=a("b622")("match");c.exports=function(h){var g;return d(h)&&
(void 0!==(g=h[f])?!!g:"RegExp"==e(h))}},"485a":function(c,b,a){b=a("da84");var d=a("c65b"),e=a("1626"),f=a("861d"),h=b.TypeError;c.exports=function(g,m){var k,l;if("string"===m&&e(k=g.toString)&&!f(l=d(k,g))||e(k=g.valueOf)&&!f(l=d(k,g))||"string"!==m&&e(k=g.toString)&&!f(l=d(k,g)))return l;throw h("Can't convert object to primitive value");}},4930:function(c,b,a){var d=a("2d00");b=a("d039");c.exports=!!Object.getOwnPropertySymbols&&!b(function(){var e=Symbol();return!String(e)||!(Object(e)instanceof
Symbol)||!Symbol.sham&&d&&41>d})},"4d64":function(c,b,a){var d=a("fc6a"),e=a("23cb"),f=a("07fa");b=function(h){return function(g,m,k){g=d(g);var l=f(g);k=e(k,l);if(h&&m!=m)for(;l>k;){if(m=g[k++],m!=m)return!0}else for(;l>k;k++)if((h||k in g)&&g[k]===m)return h||k||0;return!h&&-1}};c.exports={includes:b(!0),indexOf:b(!1)}},"4dae":function(c,b,a){b=a("da84");var d=a("23cb"),e=a("07fa"),f=a("8418"),h=b.Array,g=Math.max;c.exports=function(m,k,l){var n=e(m);k=d(k,n);l=d(void 0===l?n:l,n);n=h(g(l-k,0));
for(var q=0;k<l;k++,q++)f(n,q,m[k]);n.length=q;return n}},"4de4":function(c,b,a){c=a("23e7");var d=a("b727").filter;a=a("1dde")("filter");c({target:"Array",proto:!0,forced:!a},{filter:function(e){return d(this,e,1<arguments.length?arguments[1]:void 0)}})},"50c4":function(c,b,a){var d=a("5926"),e=Math.min;c.exports=function(f){return 0<f?e(d(f),9007199254740991):0}},5692:function(c,b,a){b=a("c430");var d=a("c6cd");(c.exports=function(e,f){return d[e]||(d[e]=void 0!==f?f:{})})("versions",[]).push({version:"3.20.1",
mode:b?"pure":"global",copyright:"\u00a9 2021 Denis Pushkarev (zloirock.ru)"})},"56ef":function(c,b,a){b=a("d066");var d=a("e330"),e=a("241c"),f=a("7418"),h=a("825a"),g=d([].concat);c.exports=b("Reflect","ownKeys")||function(m){var k=e.f(h(m)),l=f.f;return l?g(k,l(m)):k}},"577e":function(c,b,a){b=a("da84");var d=a("f5df"),e=b.String;c.exports=function(f){if("Symbol"===d(f))throw TypeError("Cannot convert a Symbol value to a string");return e(f)}},5880:function(c,b){c.exports=Y},5926:function(c,b){var a=
Math.ceil,d=Math.floor;c.exports=function(e){e=+e;return e!==e||0===e?0:(0<e?d:a)(e)}},"59ed":function(c,b,a){b=a("da84");var d=a("1626"),e=a("0d51"),f=b.TypeError;c.exports=function(h){if(d(h))return h;throw f(e(h)+" is not a function");}},"5a34":function(c,b,a){b=a("da84");var d=a("44e7"),e=b.TypeError;c.exports=function(f){if(d(f))throw e("The method doesn't accept regular expressions");return f}},"5c6c":function(c,b){c.exports=function(a,d){return{enumerable:!(a&1),configurable:!(a&2),writable:!(a&
4),value:d}}},"5e77":function(c,b,a){b=a("83ab");var d=a("1a2d");a=Function.prototype;var e=b&&Object.getOwnPropertyDescriptor,f=(d=d(a,"name"))&&"something"===function(){}.name;b=d&&(!b||b&&e(a,"name").configurable);c.exports={EXISTS:d,PROPER:f,CONFIGURABLE:b}},6547:function(c,b,a){b=a("e330");var d=a("5926"),e=a("577e"),f=a("1d80"),h=b("".charAt),g=b("".charCodeAt),m=b("".slice);a=function(k){return function(l,n){l=e(f(l));n=d(n);var q=l.length,u;if(0>n||n>=q)return k?"":void 0;var y=g(l,n);return 55296>
y||56319<y||n+1===q||56320>(u=g(l,n+1))||57343<u?k?h(l,n):y:k?m(l,n,n+2):(y-55296<<10)+(u-56320)+65536}};c.exports={codeAt:a(!1),charAt:a(!0)}},"65f0":function(c,b,a){var d=a("0b42");c.exports=function(e,f){return new (d(e))(0===f?0:f)}},"68ee":function(c,b,a){var d=a("e330");b=a("d039");var e=a("1626"),f=a("f5df"),h=a("d066"),g=a("8925"),m=function(){},k=[],l=h("Reflect","construct"),n=/^\s*(?:class|function)\b/,q=d(n.exec),u=!n.exec(m),y=function(B){if(!e(B))return!1;try{return l(m,k,B),!0}catch(C){return!1}};
a=function(B){if(!e(B))return!1;switch(f(B)){case "AsyncFunction":case "GeneratorFunction":case "AsyncGeneratorFunction":return!1}try{return u||!!q(n,g(B))}catch(C){return!0}};a.sham=!0;c.exports=!l||b(function(){var B;return y(y.call)||!y(Object)||!y(function(){B=!0})||B})?a:y},"69f3":function(c,b,a){b=a("7f9a");var d=a("da84"),e=a("e330"),f=a("861d"),h=a("9112"),g=a("1a2d"),m=a("c6cd"),k=a("f772");a=a("d012");var l=d.TypeError;d=d.WeakMap;if(b||m.state){var n=m.state||(m.state=new d),q=e(n.get),
u=e(n.has),y=e(n.set);var B=function(p,w){if(u(n,p))throw new l("Object already initialized");w.facade=p;y(n,p,w);return w};var C=function(p){return q(n,p)||{}};var r=function(p){return u(n,p)}}else{var t=k("state");a[t]=!0;B=function(p,w){if(g(p,t))throw new l("Object already initialized");w.facade=p;h(p,t,w);return w};C=function(p){return g(p,t)?p[t]:{}};r=function(p){return g(p,t)}}c.exports={set:B,get:C,has:r,enforce:function(p){return r(p)?C(p):B(p,{})},getterFor:function(p){return function(w){var x;
if(!f(w)||(x=C(w)).type!==p)throw l("Incompatible receiver, "+p+" required");return x}}}},"6eeb":function(c,b,a){var d=a("da84"),e=a("1626"),f=a("1a2d"),h=a("9112"),g=a("ce4e"),m=a("8925");b=a("69f3");var k=a("5e77").CONFIGURABLE,l=b.get,n=b.enforce,q=String(String).split("String");(c.exports=function(u,y,B,C){var r=C?!!C.unsafe:!1,t=C?!!C.enumerable:!1,p=C?!!C.noTargetGet:!1;C=C&&void 0!==C.name?C.name:y;if(e(B)){"Symbol("===String(C).slice(0,7)&&(C="["+String(C).replace(/^Symbol\(([^)]*)\)/,"$1")+
"]");(!f(B,"name")||k&&B.name!==C)&&h(B,"name",C);var w=n(B);w.source||(w.source=q.join("string"==typeof C?C:""))}u===d?t?u[y]=B:g(y,B):(r?!p&&u[y]&&(t=!0):delete u[y],t?u[y]=B:h(u,y,B))})(Function.prototype,"toString",function(){return e(this)&&l(this).source||m(this)})},7418:function(c,b){b.f=Object.getOwnPropertySymbols},"746f":function(c,b,a){var d=a("428f"),e=a("1a2d"),f=a("e538"),h=a("9bf2").f;c.exports=function(g){var m=d.Symbol||(d.Symbol={});e(m,g)||h(m,g,{value:f.f(g)})}},7839:function(c,
b){c.exports="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ")},"785a":function(c,b,a){b=(b=a("cc12")("span").classList)&&b.constructor&&b.constructor.prototype;c.exports=b===Object.prototype?void 0:b},"7b0b":function(c,b,a){b=a("da84");var d=a("1d80"),e=b.Object;c.exports=function(f){return e(d(f))}},"7c73":function(c,b,a){var d=a("825a"),e=a("37e8"),f=a("7839");b=a("d012");var h=a("1be4"),g=a("cc12"),m=a("f772")("IE_PROTO"),k=function(){},
l=function(u){u.write("<script>\x3c/script>");u.close();return u.parentWindow.Object},n,q=function(){try{n=new ActiveXObject("htmlfile")}catch(y){}if("undefined"!=typeof document)if(document.domain&&n)var u=l(n);else u=g("iframe"),u.style.display="none",h.appendChild(u),u.src="javascript:",u=u.contentWindow.document,u.open(),u.write("<script>document.F=Object\x3c/script>"),u.close(),u=u.F;else u=l(n);q=u;for(u=f.length;u--;)delete q.prototype[f[u]];return q()};b[m]=!0;c.exports=Object.create||function(u,
y){if(null!==u){k.prototype=d(u);var B=new k;k.prototype=null;B[m]=u}else B=q();return void 0===y?B:e(B,y)}},"7db0":function(c,b,a){c=a("23e7");var d=a("b727").find;a=a("44d2");var e=!0;"find"in[]&&Array(1).find(function(){e=!1});c({target:"Array",proto:!0,forced:e},{find:function(f){return d(this,f,1<arguments.length?arguments[1]:void 0)}});a("find")},"7dd0":function(c,b,a){var d=a("23e7"),e=a("c65b"),f=a("c430");b=a("5e77");var h=a("1626"),g=a("9ed3"),m=a("e163"),k=a("d2bb"),l=a("d44e"),n=a("9112"),
q=a("6eeb"),u=a("b622"),y=a("3f8c");a=a("ae93");var B=b.PROPER,C=b.CONFIGURABLE,r=a.IteratorPrototype,t=a.BUGGY_SAFARI_ITERATORS,p=u("iterator"),w=function(){return this};c.exports=function(x,z,D,E,I,W,P){g(D,z,E);E=function(O){if(O===I&&Q)return Q;if(!t&&O in J)return J[O];switch(O){case "keys":return function(){return new D(this,O)};case "values":return function(){return new D(this,O)};case "entries":return function(){return new D(this,O)}}return function(){return new D(this)}};var G=z+" Iterator",
K=!1,J=x.prototype,R=J[p]||J["@@iterator"]||I&&J[I],Q=!t&&R||E(I),N="Array"==z?J.entries||R:R,aa;N&&(x=m(N.call(new x)),x!==Object.prototype&&x.next&&(f||m(x)===r||(k?k(x,r):h(x[p])||q(x,p,w)),l(x,G,!0,!0),f&&(y[G]=w)));B&&"values"==I&&R&&"values"!==R.name&&(!f&&C?n(J,"name","values"):(K=!0,Q=function(){return e(R,this)}));if(I){var X={values:E("values"),keys:W?Q:E("keys"),entries:E("entries")};if(P)for(aa in X)!t&&!K&&aa in J||q(J,aa,X[aa]);else d({target:z,proto:!0,forced:t||K},X)}f&&!P||J[p]===
Q||q(J,p,Q,{name:I});y[z]=Q;return X}},"7f9a":function(c,b,a){var d=a("da84");b=a("1626");a=a("8925");d=d.WeakMap;c.exports=b(d)&&/native code/.test(a(d))},"825a":function(c,b,a){b=a("da84");var d=a("861d"),e=b.String,f=b.TypeError;c.exports=function(h){if(d(h))return h;throw f(e(h)+" is not an object");}},"83ab":function(c,b,a){b=a("d039");c.exports=!b(function(){return 7!=Object.defineProperty({},1,{get:function(){return 7}})[1]})},8418:function(c,b,a){var d=a("a04b"),e=a("9bf2"),f=a("5c6c");c.exports=
function(h,g,m){g=d(g);g in h?e.f(h,g,f(0,m)):h[g]=m}},"861d":function(c,b,a){var d=a("1626");c.exports=function(e){return"object"==typeof e?null!==e:d(e)}},8875:function(c,b,a){var d,e,f;(function(h,g){!(e=[],d=g,f="function"===typeof d?d.apply(b,e):d,void 0!==f&&(c.exports=f))})("undefined"!==typeof self?self:this,function(){function h(){var g=Object.getOwnPropertyDescriptor(document,"currentScript");if(!g&&"currentScript"in document&&document.currentScript||g&&g.get!==h&&document.currentScript)return document.currentScript;
try{throw Error();}catch(q){g=/@([^@]*):(\d+):(\d+)\s*$/ig;var m=/.*at [^(]*\((.*):(.+):(.+)\)$/ig.exec(q.stack)||g.exec(q.stack);g=m&&m[1]||!1;var k=m&&m[2]||!1;m=document.location.href.replace(document.location.hash,"");var l=document.getElementsByTagName("script");if(g===m){var n=document.documentElement.outerHTML;k=new RegExp("(?:[^\\n]+?\\n){0,"+(k-2)+"}[^<]*<script>([\\d\\D]*?)<\\/script>[\\d\\D]*","i");n=n.replace(k,"$1").trim()}for(k=0;k<l.length;k++)if("interactive"===l[k].readyState||l[k].src===
g||g===m&&l[k].innerHTML&&l[k].innerHTML.trim()===n)return l[k];return null}}return h})},8925:function(c,b,a){b=a("e330");var d=a("1626");a=a("c6cd");var e=b(Function.toString);d(a.inspectSource)||(a.inspectSource=function(f){return e(f)});c.exports=a.inspectSource},"8bbf":function(c,b){c.exports=Z},"90d6":function(c,b){c.exports=xa},"90e3":function(c,b,a){b=a("e330");var d=0,e=Math.random(),f=b((1).toString);c.exports=function(h){return"Symbol("+(void 0===h?"":h)+")_"+f(++d+e,36)}},9112:function(c,
b,a){b=a("83ab");var d=a("9bf2"),e=a("5c6c");c.exports=b?function(f,h,g){return d.f(f,h,e(1,g))}:function(f,h,g){f[h]=g;return f}},"94ca":function(c,b,a){var d=a("d039"),e=a("1626"),f=/#|\.prototype\./;b=function(l,n){l=g[h(l)];return l==k?!0:l==m?!1:e(n)?d(n):!!n};var h=b.normalize=function(l){return String(l).replace(f,".").toLowerCase()},g=b.data={},m=b.NATIVE="N",k=b.POLYFILL="P";c.exports=b},"99af":function(c,b,a){c=a("23e7");var d=a("da84"),e=a("d039"),f=a("e8b5"),h=a("861d"),g=a("7b0b"),m=
a("07fa"),k=a("8418"),l=a("65f0");b=a("1dde");var n=a("b622");a=a("2d00");var q=n("isConcatSpreadable"),u=d.TypeError;a=51<=a||!e(function(){var y=[];y[q]=!1;return y.concat()[0]!==y});b=b("concat");c({target:"Array",proto:!0,forced:!a||!b},{concat:function(y){var B=g(this),C=l(B,0),r=0,t;var p=-1;for(t=arguments.length;p<t;p++){var w=-1===p?B:arguments[p];var x=w;if(h(x)){var z=x[q];x=void 0!==z?!!z:f(x)}else x=!1;if(x){z=m(w);if(9007199254740991<r+z)throw u("Maximum allowed index exceeded");for(x=
0;x<z;x++,r++)x in w&&k(C,r,w[x])}else{if(9007199254740991<=r)throw u("Maximum allowed index exceeded");k(C,r++,w)}}C.length=r;return C}})},"9bf2":function(c,b,a){c=a("da84");var d=a("83ab"),e=a("0cfb"),f=a("825a"),h=a("a04b"),g=c.TypeError,m=Object.defineProperty;b.f=d?m:function(k,l,n){f(k);l=h(l);f(n);if(e)try{return m(k,l,n)}catch(q){}if("get"in n||"set"in n)throw g("Accessors not supported");"value"in n&&(k[l]=n.value);return k}},"9ed3":function(c,b,a){var d=a("ae93").IteratorPrototype,e=a("7c73"),
f=a("5c6c"),h=a("d44e"),g=a("3f8c"),m=function(){return this};c.exports=function(k,l,n,q){l+=" Iterator";k.prototype=e(d,{next:f(+!q,n)});h(k,l,!1,!0);g[l]=m;return k}},a04b:function(c,b,a){var d=a("c04e"),e=a("d9b5");c.exports=function(f){f=d(f,"string");return e(f)?f:f+""}},a434:function(c,b,a){c=a("23e7");b=a("da84");var d=a("23cb"),e=a("5926"),f=a("07fa"),h=a("7b0b"),g=a("65f0"),m=a("8418");a=a("1dde")("splice");var k=b.TypeError,l=Math.max,n=Math.min;c({target:"Array",proto:!0,forced:!a},{splice:function(q,
u){var y=h(this),B=f(y),C=d(q,B),r=arguments.length,t,p;0===r?r=t=0:1===r?(r=0,t=B-C):(r-=2,t=n(l(e(u),0),B-C));if(9007199254740991<B+r-t)throw k("Maximum allowed length exceeded");var w=g(y,t);for(p=0;p<t;p++){var x=C+p;x in y&&m(w,p,y[x])}w.length=t;if(r<t){for(p=C;p<B-t;p++){x=p+t;var z=p+r;x in y?y[z]=y[x]:delete y[z]}for(p=B;p>B-t+r;p--)delete y[p-1]}else if(r>t)for(p=B-t;p>C;p--)x=p+t-1,z=p+r-1,x in y?y[z]=y[x]:delete y[z];for(p=0;p<r;p++)y[p+C]=arguments[p+2];y.length=B-t+r;return w}})},a4d3:function(c,
b,a){c=a("23e7");var d=a("da84"),e=a("d066"),f=a("2ba4"),h=a("c65b"),g=a("e330"),m=a("c430"),k=a("83ab"),l=a("4930"),n=a("d039"),q=a("1a2d"),u=a("e8b5"),y=a("1626"),B=a("861d"),C=a("3a9b"),r=a("d9b5"),t=a("825a"),p=a("7b0b"),w=a("fc6a"),x=a("a04b"),z=a("577e"),D=a("5c6c"),E=a("7c73"),I=a("df75"),W=a("241c"),P=a("057f"),G=a("7418"),K=a("06cf"),J=a("9bf2"),R=a("d1e7"),Q=a("f36a");b=a("6eeb");var N=a("5692"),aa=a("f772"),X=a("d012"),O=a("90e3"),oa=a("b622"),ya=a("e538"),za=a("746f"),Aa=a("d44e"),pa=
a("69f3"),da=a("b727").forEach,L=aa("hidden");a=oa("toPrimitive");var Ba=pa.set,qa=pa.getterFor("Symbol"),M=Object.prototype,S=d.Symbol,U=S&&S.prototype,ra=d.TypeError;d=d.QObject;var ba=e("JSON","stringify"),sa=K.f,V=J.f,ta=P.f,Ca=R.f,ua=g([].push),T=N("symbols"),ca=N("op-symbols"),ha=N("string-to-symbol-registry"),ia=N("symbol-to-string-registry");e=N("wks");var ja=!d||!d.prototype||!d.prototype.findChild,ka=k&&n(function(){return 7!=E(V({},"a",{get:function(){return V(this,"a",{value:7}).a}})).a})?
function(v,A,F){var H=sa(M,A);H&&delete M[A];V(v,A,F);H&&v!==M&&V(M,A,H)}:V,la=function(v,A){var F=T[v]=E(U);Ba(F,{type:"Symbol",tag:v,description:A});k||(F.description=A);return F},ea=function(v,A,F){v===M&&ea(ca,A,F);t(v);A=x(A);t(F);return q(T,A)?(F.enumerable?(q(v,L)&&v[L][A]&&(v[L][A]=!1),F=E(F,{enumerable:D(0,!1)})):(q(v,L)||V(v,L,D(1,{})),v[L][A]=!0),ka(v,A,F)):V(v,A,F)},va=function(v,A){t(v);var F=w(A);A=I(F).concat(ma(F));da(A,function(H){k&&!h(na,F,H)||ea(v,H,F[H])});return v},na=function(v){v=
x(v);var A=h(Ca,this,v);return this===M&&q(T,v)&&!q(ca,v)?!1:A||!q(this,v)||!q(T,v)||q(this,L)&&this[L][v]?A:!0};g=function(v,A){v=w(v);A=x(A);if(v!==M||!q(T,A)||q(ca,A)){var F=sa(v,A);!F||!q(T,A)||q(v,L)&&v[L][A]||(F.enumerable=!0);return F}};N=function(v){v=ta(w(v));var A=[];da(v,function(F){q(T,F)||q(X,F)||ua(A,F)});return A};var ma=function(v){var A=v===M;v=ta(A?ca:w(v));var F=[];da(v,function(H){!q(T,H)||A&&!q(M,H)||ua(F,T[H])});return F};l||(S=function(){if(C(U,this))throw ra("Symbol is not a constructor");
var v=arguments.length&&void 0!==arguments[0]?z(arguments[0]):void 0,A=O(v),F=function(H){this===M&&h(F,ca,H);q(this,L)&&q(this[L],A)&&(this[L][A]=!1);ka(this,A,D(1,H))};k&&ja&&ka(M,A,{configurable:!0,set:F});return la(A,v)},U=S.prototype,b(U,"toString",function(){return qa(this).tag}),b(S,"withoutSetter",function(v){return la(O(v),v)}),R.f=na,J.f=ea,K.f=g,W.f=P.f=N,G.f=ma,ya.f=function(v){return la(oa(v),v)},k&&(V(U,"description",{configurable:!0,get:function(){return qa(this).description}}),m||
b(M,"propertyIsEnumerable",na,{unsafe:!0})));c({global:!0,wrap:!0,forced:!l,sham:!l},{Symbol:S});da(I(e),function(v){za(v)});c({target:"Symbol",stat:!0,forced:!l},{"for":function(v){v=z(v);if(q(ha,v))return ha[v];var A=S(v);ha[v]=A;ia[A]=v;return A},keyFor:function(v){if(!r(v))throw ra(v+" is not a symbol");if(q(ia,v))return ia[v]},useSetter:function(){ja=!0},useSimple:function(){ja=!1}});c({target:"Object",stat:!0,forced:!l,sham:!k},{create:function(v,A){return void 0===A?E(v):va(E(v),A)},defineProperty:ea,
defineProperties:va,getOwnPropertyDescriptor:g});c({target:"Object",stat:!0,forced:!l},{getOwnPropertyNames:N,getOwnPropertySymbols:ma});c({target:"Object",stat:!0,forced:n(function(){G.f(1)})},{getOwnPropertySymbols:function(v){return G.f(p(v))}});ba&&(m=!l||n(function(){var v=S();return"[null]"!=ba([v])||"{}"!=ba({a:v})||"{}"!=ba(Object(v))}),c({target:"JSON",stat:!0,forced:m},{stringify:function(v,A,F){var H=Q(arguments),wa=A;if((B(A)||void 0!==v)&&!r(v))return u(A)||(A=function(Da,fa){y(wa)&&
(fa=h(wa,this,Da,fa));if(!r(fa))return fa}),H[1]=A,f(ba,null,H)}}));if(!U[a]){var Ea=U.valueOf;b(U,a,function(v){return h(Ea,this)})}Aa(S,"Symbol");X[L]=!0},a640:function(c,b,a){var d=a("d039");c.exports=function(e,f){var h=[][e];return!!h&&d(function(){h.call(null,f||function(){throw 1;},1)})}},ab13:function(c,b,a){var d=a("b622")("match");c.exports=function(e){var f=/./;try{"/./"[e](f)}catch(h){try{return f[d]=!1,"/./"[e](f)}catch(g){}}return!1}},ad6d:function(c,b,a){var d=a("825a");c.exports=function(){var e=
d(this),f="";e.global&&(f+="g");e.ignoreCase&&(f+="i");e.multiline&&(f+="m");e.dotAll&&(f+="s");e.unicode&&(f+="u");e.sticky&&(f+="y");return f}},ae93:function(c,b,a){b=a("d039");var d=a("1626"),e=a("7c73"),f=a("e163"),h=a("6eeb"),g=a("b622");a=a("c430");var m=g("iterator");g=!1;var k;if([].keys){var l=[].keys();"next"in l?(f=f(f(l)),f!==Object.prototype&&(k=f)):g=!0}void 0==k||b(function(){var n={};return k[m].call(n)!==n})?k={}:a&&(k=e(k));d(k[m])||h(k,m,function(){return this});c.exports={IteratorPrototype:k,
BUGGY_SAFARI_ITERATORS:g}},b041:function(c,b,a){b=a("00ee");var d=a("f5df");c.exports=b?{}.toString:function(){return"[object "+d(this)+"]"}},b0c0:function(c,b,a){c=a("83ab");b=a("5e77").EXISTS;var d=a("e330");a=a("9bf2").f;var e=Function.prototype,f=d(e.toString),h=/function\b(?:\s|\/\*[\S\s]*?\*\/|\/\/[^\n\r]*[\n\r]+)*([^\s(/]*)/,g=d(h.exec);c&&!b&&a(e,"name",{configurable:!0,get:function(){try{return g(h,f(this))[1]}catch(m){return""}}})},b622:function(c,b,a){b=a("da84");var d=a("5692"),e=a("1a2d"),
f=a("90e3"),h=a("4930"),g=a("fdbf"),m=d("wks"),k=b.Symbol,l=k&&k["for"],n=g?k:k&&k.withoutSetter||f;c.exports=function(q){if(!e(m,q)||!h&&"string"!=typeof m[q]){var u="Symbol."+q;h&&e(k,q)?m[q]=k[q]:m[q]=g&&l?l(u):n(u)}return m[q]}},b64b:function(c,b,a){c=a("23e7");var d=a("7b0b"),e=a("df75");a=a("d039")(function(){e(1)});c({target:"Object",stat:!0,forced:a},{keys:function(f){return e(d(f))}})},b727:function(c,b,a){var d=a("0366");b=a("e330");var e=a("44ad"),f=a("7b0b"),h=a("07fa"),g=a("65f0"),m=
b([].push);a=function(k){var l=1==k,n=2==k,q=3==k,u=4==k,y=6==k,B=7==k,C=5==k||y;return function(r,t,p,w){var x=f(r),z=e(x);t=d(t,p);p=h(z);var D=0;w=w||g;r=l?w(r,p):n||B?w(r,0):void 0;for(var E;p>D;D++)if(C||D in z)if(w=z[D],E=t(w,D,x),k)if(l)r[D]=E;else if(E)switch(k){case 3:return!0;case 5:return w;case 6:return D;case 2:m(r,w)}else switch(k){case 4:return!1;case 7:m(r,w)}return y?-1:q||u?u:r}};c.exports={forEach:a(0),map:a(1),filter:a(2),some:a(3),every:a(4),find:a(5),findIndex:a(6),filterReject:a(7)}},
c04e:function(c,b,a){b=a("da84");var d=a("c65b"),e=a("861d"),f=a("d9b5"),h=a("dc4a"),g=a("485a");a=a("b622");var m=b.TypeError,k=a("toPrimitive");c.exports=function(l,n){if(!e(l)||f(l))return l;var q=h(l,k);if(q){void 0===n&&(n="default");l=d(q,l,n);if(!e(l)||f(l))return l;throw m("Can't convert object to primitive value");}void 0===n&&(n="number");return g(l,n)}},c430:function(c,b){c.exports=!1},c65b:function(c,b){var a=Function.prototype.call;c.exports=a.bind?a.bind(a):function(){return a.apply(a,
arguments)}},c6b6:function(c,b,a){b=a("e330");var d=b({}.toString),e=b("".slice);c.exports=function(f){return e(d(f),8,-1)}},c6cd:function(c,b,a){b=a("da84");a=a("ce4e");a=b["__core-js_shared__"]||a("__core-js_shared__",{});c.exports=a},c8ba:function(c,b){b=function(){return this}();try{b=b||(new Function("return this"))()}catch(a){"object"===typeof window&&(b=window)}c.exports=b},ca84:function(c,b,a){b=a("e330");var d=a("1a2d"),e=a("fc6a"),f=a("4d64").indexOf,h=a("d012"),g=b([].push);c.exports=function(m,
k){m=e(m);var l=0,n=[],q;for(q in m)!d(h,q)&&d(m,q)&&g(n,q);for(;k.length>l;)d(m,q=k[l++])&&(~f(n,q)||g(n,q));return n}},caad:function(c,b,a){c=a("23e7");var d=a("4d64").includes;a=a("44d2");c({target:"Array",proto:!0},{includes:function(e){return d(this,e,1<arguments.length?arguments[1]:void 0)}});a("includes")},cc12:function(c,b,a){b=a("da84");a=a("861d");var d=b.document,e=a(d)&&a(d.createElement);c.exports=function(f){return e?d.createElement(f):{}}},ce4e:function(c,b,a){var d=a("da84"),e=Object.defineProperty;
c.exports=function(f,h){try{e(d,f,{value:h,configurable:!0,writable:!0})}catch(g){d[f]=h}return h}},d012:function(c,b){c.exports={}},d039:function(c,b){c.exports=function(a){try{return!!a()}catch(d){return!0}}},d066:function(c,b,a){var d=a("da84"),e=a("1626");c.exports=function(f,h){if(2>arguments.length){var g=d[f];g=e(g)?g:void 0}else g=d[f]&&d[f][h];return g}},d1e7:function(c,b,a){c={}.propertyIsEnumerable;var d=Object.getOwnPropertyDescriptor;a=d&&!c.call({1:2},1);b.f=a?function(e){e=d(this,e);
return!!e&&e.enumerable}:c},d28b:function(c,b,a){a("746f")("iterator")},d2bb:function(c,b,a){var d=a("e330"),e=a("825a"),f=a("3bbe");c.exports=Object.setPrototypeOf||("__proto__"in{}?function(){var h=!1,g={};try{var m=d(Object.getOwnPropertyDescriptor(Object.prototype,"__proto__").set);m(g,[]);h=g instanceof Array}catch(k){}return function(k,l){e(k);f(l);h?m(k,l):k.__proto__=l;return k}}():void 0)},d3b7:function(c,b,a){c=a("00ee");b=a("6eeb");a=a("b041");c||b(Object.prototype,"toString",a,{unsafe:!0})},
d44e:function(c,b,a){var d=a("9bf2").f,e=a("1a2d"),f=a("b622")("toStringTag");c.exports=function(h,g,m){h&&!m&&(h=h.prototype);h&&!e(h,f)&&d(h,f,{configurable:!0,value:g})}},d81d:function(c,b,a){c=a("23e7");var d=a("b727").map;a=a("1dde")("map");c({target:"Array",proto:!0,forced:!a},{map:function(e){return d(this,e,1<arguments.length?arguments[1]:void 0)}})},d9b5:function(c,b,a){b=a("da84");var d=a("d066"),e=a("1626"),f=a("3a9b");a=a("fdbf");var h=b.Object;c.exports=a?function(g){return"symbol"==
typeof g}:function(g){var m=d("Symbol");return e(m)&&f(m.prototype,h(g))}},da84:function(c,b,a){(function(d){var e=function(f){return f&&f.Math==Math&&f};c.exports=e("object"==typeof globalThis&&globalThis)||e("object"==typeof window&&window)||e("object"==typeof self&&self)||e("object"==typeof d&&d)||function(){return this}()||Function("return this")()}).call(this,a("c8ba"))},dbb4:function(c,b,a){c=a("23e7");b=a("83ab");var d=a("56ef"),e=a("fc6a"),f=a("06cf"),h=a("8418");c({target:"Object",stat:!0,
sham:!b},{getOwnPropertyDescriptors:function(g){g=e(g);for(var m=f.f,k=d(g),l={},n=0,q,u;k.length>n;)u=m(g,q=k[n++]),void 0!==u&&h(l,q,u);return l}})},dc4a:function(c,b,a){var d=a("59ed");c.exports=function(e,f){e=e[f];return null==e?void 0:d(e)}},ddb0:function(c,b,a){c=a("da84");var d=a("fdbc");b=a("785a");var e=a("e260"),f=a("9112");a=a("b622");var h=a("iterator"),g=a("toStringTag"),m=e.values;a=function(l,n){if(l){if(l[h]!==m)try{f(l,h,m)}catch(u){l[h]=m}l[g]||f(l,g,n);if(d[n])for(var q in e)if(l[q]!==
e[q])try{f(l,q,e[q])}catch(u){l[q]=e[q]}}};for(var k in d)a(c[k]&&c[k].prototype,k);a(b,"DOMTokenList")},df75:function(c,b,a){var d=a("ca84"),e=a("7839");c.exports=Object.keys||function(f){return d(f,e)}},e01a:function(c,b,a){c=a("23e7");var d=a("83ab"),e=a("da84");b=a("e330");var f=a("1a2d"),h=a("1626"),g=a("3a9b"),m=a("577e"),k=a("9bf2").f;a=a("e893");var l=e.Symbol,n=l&&l.prototype;if(d&&h(l)&&(!("description"in n)||void 0!==l().description)){var q={};d=function(){var p=1>arguments.length||void 0===
arguments[0]?void 0:m(arguments[0]),w=g(n,this)?new l(p):void 0===p?l():l(p);""===p&&(q[w]=!0);return w};a(d,l);d.prototype=n;n.constructor=d;var u="Symbol(test)"==String(l("test")),y=b(n.toString),B=b(n.valueOf),C=/^Symbol\((.*)\)[^)]+$/,r=b("".replace),t=b("".slice);k(n,"description",{configurable:!0,get:function(){var p=B(this),w=y(p);if(f(q,p))return"";p=u?t(w,7,-1):r(w,C,"$1");return""===p?void 0:p}});c({global:!0,forced:!0},{Symbol:d})}},e163:function(c,b,a){b=a("da84");var d=a("1a2d"),e=a("1626"),
f=a("7b0b"),h=a("f772");a=a("e177");var g=h("IE_PROTO"),m=b.Object,k=m.prototype;c.exports=a?m.getPrototypeOf:function(l){l=f(l);if(d(l,g))return l[g];var n=l.constructor;return e(n)&&l instanceof n?n.prototype:l instanceof m?k:null}},e177:function(c,b,a){b=a("d039");c.exports=!b(function(){function d(){}d.prototype.constructor=null;return Object.getPrototypeOf(new d)!==d.prototype})},e260:function(c,b,a){var d=a("fc6a");b=a("44d2");var e=a("3f8c"),f=a("69f3"),h=a("9bf2").f,g=a("7dd0"),m=a("c430");
a=a("83ab");var k=f.set,l=f.getterFor("Array Iterator");c.exports=g(Array,"Array",function(n,q){k(this,{type:"Array Iterator",target:d(n),index:0,kind:q})},function(){var n=l(this),q=n.target,u=n.kind,y=n.index++;return!q||y>=q.length?(n.target=void 0,{value:void 0,done:!0}):"keys"==u?{value:y,done:!1}:"values"==u?{value:q[y],done:!1}:{value:[y,q[y]],done:!1}},"values");c=e.Arguments=e.Array;b("keys");b("values");b("entries");if(!m&&a&&"values"!==c.name)try{h(c,"name",{value:"values"})}catch(n){}},
e330:function(c,b){b=Function.prototype;var a=b.bind,d=b.call,e=a&&a.bind(d);c.exports=a?function(f){return f&&e(d,f)}:function(f){return f&&function(){return d.apply(f,arguments)}}},e439:function(c,b,a){c=a("23e7");b=a("d039");var d=a("fc6a"),e=a("06cf").f;a=a("83ab");b=b(function(){e(1)});c({target:"Object",stat:!0,forced:!a||b,sham:!a},{getOwnPropertyDescriptor:function(f,h){return e(d(f),h)}})},e538:function(c,b,a){c=a("b622");b.f=c},e893:function(c,b,a){var d=a("1a2d"),e=a("56ef"),f=a("06cf"),
h=a("9bf2");c.exports=function(g,m,k){for(var l=e(m),n=h.f,q=f.f,u=0;u<l.length;u++){var y=l[u];d(g,y)||k&&d(k,y)||n(g,y,q(m,y))}}},e8b5:function(c,b,a){var d=a("c6b6");c.exports=Array.isArray||function(e){return"Array"==d(e)}},f36a:function(c,b,a){b=a("e330");c.exports=b([].slice)},f5df:function(c,b,a){b=a("da84");var d=a("00ee"),e=a("1626"),f=a("c6b6"),h=a("b622")("toStringTag"),g=b.Object,m="Arguments"==f(function(){return arguments}());c.exports=d?f:function(k){var l;if(void 0===k)var n="Undefined";
else{if(null===k)var q="Null";else{a:{var u=k=g(k);try{q=u[h];break a}catch(y){}q=void 0}q="string"==typeof(n=q)?n:m?f(k):"Object"==(l=f(k))&&e(k.callee)?"Arguments":l}n=q}return n}},f772:function(c,b,a){b=a("5692");var d=a("90e3"),e=b("keys");c.exports=function(f){return e[f]||(e[f]=d(f))}},fae3:function(c,b,a){function d(r,t){for(var p=0;p<t.length;p++){var w=t[p];w.enumerable=w.enumerable||!1;w.configurable=!0;"value"in w&&(w.writable=!0);Object.defineProperty(r,w.key,w)}}function e(r,t,p){t&&
d(r.prototype,t);p&&d(r,p);Object.defineProperty(r,"prototype",{writable:!1});return r}function f(r){"@babel/helpers - typeof";return f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t},f(r)}function h(r,t){var p=Object.keys(r);if(Object.getOwnPropertySymbols){var w=Object.getOwnPropertySymbols(r);t&&(w=w.filter(function(x){return Object.getOwnPropertyDescriptor(r,
x).enumerable}));p.push.apply(p,w)}return p}function g(r){for(var t=1;t<arguments.length;t++){var p=null!=arguments[t]?arguments[t]:{};t%2?h(Object(p),!0).forEach(function(w){var x=p[w];w in r?Object.defineProperty(r,w,{value:x,enumerable:!0,configurable:!0,writable:!0}):r[w]=x}):Object.getOwnPropertyDescriptors?Object.defineProperties(r,Object.getOwnPropertyDescriptors(p)):h(Object(p)).forEach(function(w){Object.defineProperty(r,w,Object.getOwnPropertyDescriptor(p,w))})}return r}function m(){return Object(l.useStore)(u)}
function k(){var r=Object(l.useStore)(u),t=Object(n.inject)("getCurrentWidget");if(t){var p=t();var w=g(g({},r.state.widgets.find(function(x){return x.name===p})),{},{onUpdate:function(x){if(w)C.on(w.name,x);Object(n.onUnmounted)(function(){w&&C.off(w.name,x)})}})}return{currentWidget:w,getWidget:function(x){var z=r.state.widgets.find(function(D){return D.name===x});return z?g(g({},z),{},{onUpdate:function(D){if(z)C.on(z.name,D);Object(n.onUnmounted)(function(){C.off(z.name,D)})}}):null},updateWidget:function(x){for(var z=
arguments.length,D=Array(1<z?z-1:0),E=1;E<z;E++)D[E-1]=arguments[E];C.emit.apply(C,[x].concat(D))},isActivate:function(x){var z=r.state.widgets.find(function(D){return D.name===x});return z?z.visible:!1},activate:function(x){var z=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,D=[];Array.isArray(x)?D=x:D.push(x);console.log(D);D.forEach(function(E){E="string"===typeof E?{reload:z,name:E}:g({reload:z},E);r.dispatch("activate",E)})},disable:function(x){var z=[];Array.isArray(x)?z=x:z.push(x);
z.forEach(function(D){r.dispatch("disable",D)})},disableAll:function(){r.dispatch("disableAll",0<arguments.length&&void 0!==arguments[0]?arguments[0]:!1)}}}a.r(b);a.d(b,"getInjectKey",function(){return y});a.d(b,"injectState",function(){return B});a.d(b,"useWidgetStore",function(){return m});a.d(b,"useWidget",function(){return k});"undefined"!==typeof window&&(c=window.document.currentScript,b=a("8875"),c=b(),"currentScript"in document||Object.defineProperty(document,"currentScript",{get:b}),c=c&&
c.src.match(/(.+\/)[^/]+\.js(\?.*)?$/))&&(a.p=c[1]);a("a4d3");a("e01a");a("d3b7");a("d28b");a("e260");a("3ca3");a("ddb0");a("b64b");a("4de4");a("e439");a("159b");a("dbb4");a("25f0");a("d81d");a("caad");a("2532");a("b0c0");a("7db0");a("a434");a("99af");var l=a("5880"),n=a("8bbf"),q=a("90d6"),u,y=function(){return u=(new Date).getTime().toString()},B=function(r){var t;"function"===typeof r.state&&(r.state=r.state()||{});var p=g({autoDisable:!0,disableOther:!1},r.state.defaultOption),w=null===(t=r.state)||
void 0===t?void 0:t.openAtStart;if(r){var x;t=null===(x=r.state)||void 0===x?void 0:x.widgets.map(function(z){return g(g(g({visible:null===w||void 0===w?void 0:w.includes(z.name)},p),z),{},{meta:g(g({},p.meta),z.meta),key:Object(q.v4)()})});r.state.widgets=t}else throw Error("injectState \u53c2\u6570\u4e0d\u80fd\u4e3a\u7a7a");return Object(l.createStore)({state:g(g({widgets:[],openAtStart:[]},r.state),{},{defaultOption:p}),getters:g({},r.getters),mutations:g({addAlive:function(z,D){z.openAtStart.includes(D)||
z.openAtStart.push(D)}},r.mutations),actions:g({activate:function(z,D){var E=z.commit,I=z.state,W=z.dispatch,P="string"===typeof D?D:D.name,G=I.widgets.find(function(K){return K.name===P});G?(G.visible&&D.reload&&(G.visible=!1,G.key=Object(q.v4)()),Object(n.nextTick)(function(){"object"===f(D)&&null!==D&&D.data&&(G.data=D.data);G.visible=!0}),I.widgets.forEach(function(K){G.name!==K.name&&(G.group&&K.group===G.group&&(K.visible=!1),Array.isArray(G.disableOther)?G.disableOther.forEach(function(J){W("disable",
J)}):G.disableOther&&K.autoDisable&&(K.visible=!1))}),I.openAtStart.includes(P)||E("addAlive",P)):console.log("widget\u4e0d\u5b58\u5728",D)},disable:function(z,D){var E=z.state;if(z=E.widgets.find(function(I,W){return I.name===D?(delete E.widgets[W].data,!0):!1}))z.visible=!1},disableAll:function(z,D){z.state.widgets.forEach(function(E){E.visible&&(D||E.autoDisable)&&(E.visible=!1)})}},r.actions)})},C=new (function(){function r(){if(!(this instanceof r))throw new TypeError("Cannot call a class as a function");
this._cache={}}e(r,[{key:"on",value:function(t,p){t=this._cache[t]=this._cache[t]||[];-1===t.indexOf(p)&&t.push(p);return this}},{key:"emit",value:function(t){for(var p=arguments.length,w=Array(1<p?p-1:0),x=1;x<p;x++)w[x-1]=arguments[x];p=this._cache[t];Array.isArray(p)&&p.forEach(function(z){z.apply(void 0,w)});return this}},{key:"off",value:function(t,p){t=this._cache[t];Array.isArray(t)&&(p?(p=t.indexOf(p),-1!==p&&t.splice(p,1)):t.length=0);return this}}]);return r}())},fc6a:function(c,b,a){var d=
a("44ad"),e=a("1d80");c.exports=function(f){return d(e(f))}},fdbc:function(c,b){c.exports={CSSRuleList:0,CSSStyleDeclaration:0,CSSValueList:0,ClientRectList:0,DOMRectList:0,DOMStringList:0,DOMTokenList:1,DataTransferItemList:0,FileList:0,HTMLAllCollection:0,HTMLCollection:0,HTMLFormElement:0,HTMLSelectElement:0,MediaList:0,MimeTypeArray:0,NamedNodeMap:0,NodeList:1,PaintRequestList:0,Plugin:0,PluginArray:0,SVGLengthList:0,SVGNumberList:0,SVGPathSegList:0,SVGPointList:0,SVGStringList:0,SVGTransformList:0,
SourceBufferList:0,StyleSheetList:0,TextTrackCueList:0,TextTrackList:0,TouchList:0}},fdbf:function(c,b,a){b=a("4930");c.exports=b&&!Symbol.sham&&"symbol"==typeof Symbol.iterator}})});
